### ISSUE TITLE
Errors without trailing slash

### ISSUE THREAD

**Issue by iltimasd** [digitalinteraction/vercel-netlify-cms-github#1]
I tried setting this up and kept getting a 404 error on the /admin page about not finding config.yml

It seems this has to do with how the Netlify lib looks for the yml, since vercel drop trailing slashes it ends up looking for `/adminconfig.yml` instead of `/admin/config.yml`

I fixed it by adding a `vercel.json` file and added `{ "trailingSlash": true }`

**Comment by robb-j** [comment]
Thanks for the report, I hadn't noticed that. I'll update the readme to point this out.
