### ISSUE TITLE
Can't access private repository

### ISSUE THREAD

**Issue by jajaperson** [digitalinteraction/vercel-netlify-cms-github#10]
After following the instructions, and logging in to the admin page I get the following error:

> Repo "jajaperson/[the repository]" not found.
> 
> Please ensure the repo information is spelled correctly.
> 
> If the repo is private, make sure you're logged into a GitHub account with access.
> 
> If your repo is under an organization, ensure the organization has granted access to Netlify
> CMS.

Any ideas why this might be happening?

**Comment by jajaperson** [comment]
Never mind, I seem to have got it working!

**Comment by robb-j** [comment]
I'm glad you got it sorted! I'd be interesting to know what went wrong and if there's anything I can do to improve the docs!

**Comment by jajaperson** [comment]
so basically it looks like the problem is, if you only enable the github app in the pop up when logging into cms, it doesn't have access to your repositories, since it is set up as "authorized" but not "installed". if you install the app directly from the GitHub app's page, the problem goes away.
