### ISSUE TITLE
how to use astro project

### ISSUE THREAD

**Issue by pipinosuke** [digitalinteraction/vercel-netlify-cms-github#12]
Hi 
i tried my astro project, but it didnt work auth and callback. 
what should i do? 

astro endpoint reference is below
https://docs.astro.build/core-concepts/endpoints/

thanks

**Comment by pipinosuke** [comment]
this is my situation

i go to /admin and click login with button. Then, cause 404 error.(No webpage was found for the web address: )

**Comment by robb-j** [comment]
Hi, I'm not familiar with Astro and/or deploying it on Vercel. It [looks like](https://vercel.com/docs/frameworks/astro#using-the-/api-directory) you can still have the usual vercel edge functions in the `/api` directory so it might be able to work but I do not know. If you have the endpoints in the places suggested in this project's readme then go through a login flow with the browser developer tools's network tab wit `Preserve log` turned on, you should see what requests are going on and which one(s) are failing?
