### ISSUE TITLE
Callback stuck at "Authorized, closing ..."

### ISSUE THREAD

**Issue by andreademasi** [digitalinteraction/vercel-netlify-cms-github#3]
As stated in the title, a new window for the auth flow opens but it doesn't close and remains close at "Authorized, closing ...".

**Comment by robb-j** [comment]
Hey, have you followed all of the steps in the README.md? And is there anything in the browser console when it is stuck on that page? You might have to enable "Preserve Log" or similar so the logs don't reset on page redirections.

**Comment by robb-j** [comment]
I've not heard back from you, if you're still having trouble feel free to re-open this issue

**Comment by colaquecez** [comment]
i`m have the same error :(
