### ISSUE TITLE
Docusaurus 2

### ISSUE THREAD

**Issue by mdestafadilah** [digitalinteraction/vercel-netlify-cms-github#7]
Hi, It's work with docusaurus? anyone have idea?

Thanks.

**Comment by robb-j** [comment]
Hi, I don't know docusaurus. If you can normally edit it with netlify-cms and you want to host it on Vercel, you probably can! I don't know the specific configuration you might need though.

**Comment by mdestafadilah** [comment]
I'm testing without docusaurus for first setup, but i'm not able to login, any update config in vercel also?

**Comment by robb-j** [comment]
You should be able to find everything in the README.md, feel free to reopen this if you have any issues.
