### ISSUE TITLE
Authorized, closing ...

### ISSUE THREAD

**Issue by colaquecez** [digitalinteraction/vercel-netlify-cms-github#8]
The screen never change, any one know how fix it?
![image](https://user-images.githubusercontent.com/38195454/137516015-f24e248b-8496-4da9-ab2b-3ac1dc9e5873.png)

**Comment by robb-j** [comment]
Hey, I've been on holiday for a little while. Are you still having this issue? This info would help:

- Do you have "enforce trailing slashes enabled", this solves lots of issues I've had (I should probably make it a mandatory step)
- What's the structure of your repo, I posted my usual structure here (I should also update the readme to include this I guess) https://github.com/digitalinteraction/vercel-netlify-cms-github/issues/6#issuecomment-917478921
- What's the content of your netlify `config.yml` file?

**Comment by robb-j** [comment]
I've not heard back from you, please reopen if you're still getting this error.

**Comment by jlameira** [comment]
@robb-j 
I had the same issue, but I can't fix it. 
I don't know what's happening.

![Captura de Tela 2023-07-15 às 18 31 06](https://github.com/digitalinteraction/vercel-netlify-cms-github/assets/8197441/1d6190a1-8867-4244-900a-8c17e8c3c72c)
![Captura de Tela 2023-07-15 às 18 32 48](https://github.com/digitalinteraction/vercel-netlify-cms-github/assets/8197441/0237389a-6575-4b25-9465-62208251a2fc)
![Captura de Tela 2023-07-15 às 18 36 22](https://github.com/digitalinteraction/vercel-netlify-cms-github/assets/8197441/2eef7e8a-fec0-4ef9-8a82-dd2410c2537c)
